First pass at release through Github actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,16 +5,24 @@ on:
   - pull_request
 
 jobs:
+  # Main CI: this will test the library against all target versions on Linux and
+  # one version on Mac OS (3.8) to mirror development environment.
   check:
     runs-on: ${{ matrix.os }}
 
     strategy:
       fail-fast: false
       matrix:
-        python: [3.5, 3.6, 3.7, 3.8, pypy3]
-        os: [ubuntu-latest, macos-latest]
+        python:
+          - 3.5
+          - 3.6
+          - 3.7
+          - 3.8
+          - pypy3
+        os:
+          - ubuntu-latest
+          - macos-latest
         exclude:
-          # Testing on macos mostly to make sure dev doesn't break.
           - os: macos-latest
             python: 3.5
           - os: macos-latest
@@ -25,9 +33,7 @@ jobs:
             python: pypy3
 
     steps:
-      - uses: actions/checkout@v1
-        with:
-          fetch-depth: 1
+      - uses: actions/checkout@v2
 
       - name: Set up Python
         uses: actions/setup-python@v1
@@ -113,19 +119,15 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
 
+  # Build wheels and source distribution, upload them as build artifacts.
   build:
     runs-on: ubuntu-latest
 
     needs:
       - check
 
-    strategy:
-      fail-fast: false
-
     steps:
-      - uses: actions/checkout@v1
-        with:
-          fetch-depth: 1
+      - uses: actions/checkout@v2
 
       - name: Set up Python
         uses: actions/setup-python@v1
@@ -158,3 +160,88 @@ jobs:
         with:
           name: dist
           path: dist
+
+  # On tag this should create a Github release with the same tag and upload the
+  # artifacts from the `build` step.
+  # TODO: Upload to PyPI?
+  release:
+    runs-on: ubuntu-latest
+    needs: [check, build]
+
+    if: success() && contains(github.ref, 'tags/v')
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.8
+
+      # TODO: Check tag matches actual package version.
+      - name: Inspect and check version
+        id: version
+        run: |
+          version_str=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
+
+          if ! grep -q -P '^\d+\.\d+\.\d+(?:\.(?:dev|a|b|rc)\d+)?$' <<< "$version_str"; then
+            echo "::error::Invalid version string $version_str"
+            exit 1
+          fi
+
+          prerelease=$(grep -q -P '\.(?:dev|a|b|rc)\d+$' <<< "$version_str" && echo true || echo false)
+
+          echo "::set-output name=version::${version_str}"
+          echo "::set-output name=prerelease::${prerelease}"
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v1
+        with:
+          name: dist
+
+      - name: Create body
+        id: body
+        run: |
+          body=$(cat <<EOF
+          Release ${{ steps.version.outputs.version }} ($(date -I))
+
+          \`\`\`
+          $(cat dist/checksums.txt)
+          \`\`\`
+          EOF
+          )
+          escaped="${body//$'\n'/%0A}"
+          echo "::set-output name=value::$escaped"
+
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.version.outputs.version }}
+          release_name: Release ${{ steps.version.outputs.version }}
+          body: ${{ steps.body.outputs.value }}
+          prerelease: ${{ steps.version.outputs.prerelease }}
+          draft: true # Let a human promote releases for now
+
+      # I'd like to use actions/upload-release-asset but it doesn't support
+      # globs/dynamic file lists at the moment.
+      - name: Upload release artifacts
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          AUTH="Authorization: token $GITHUB_TOKEN"
+          URL="https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets"
+
+          for file in dist/*; do
+              echo "Uploading $file...\n"
+              curl \
+                --verbose \
+                --fail \
+                -H "$AUTH" \
+                -H "Content-Type: $(file -b --mime-type "$file")" \
+                -H "Content-Length: $(stat -c%s "$file")" \
+                --data-binary @"$file" \
+                "$URL?name=$(basename "$file")"
+          done
