Check that tag matches package version

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -178,14 +178,19 @@ jobs:
         with:
           python-version: 3.8
 
-      # TODO: Check tag matches actual package version.
       - name: Inspect and check version
         id: version
         run: |
           version_str=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
+          package_version=$(grep __version__ py_gql/_pkg.py | sed 's/__version__ = //; s/\"//g')
 
           if ! grep -q -P '^\d+\.\d+\.\d+(?:\.(?:dev|a|b|rc)\d+)?$' <<< "$version_str"; then
             echo "::error::Invalid version string $version_str"
+            exit 1
+          fi
+
+          if [ "$version_str" != "$package_version" ]; then
+            echo "::error::Tag ($version_str) should match package version ($package_version)"
             exit 1
           fi
 
